export const ERROR_MESSAGE = {
  INVALID_CREDENTIALS: 'メールアドレスまたはパスワードが正しくありません',
  ALREADY_EXISTS_USER: 'メールアドレスまたはユーザー名が既に使用されています',
  REQUIRED_EMAIL: 'メールアドレスを入力してください',
  INVALID_EMAIL: 'メールアドレスが不正です',
  TOO_LONG_EMAIL: 'メールアドレスは128文字以下で入力してください',
  REQUIRED_PASSWORD: 'パスワードを入力してください',
  WEAK_PASSWORD: 'パスワードは8文字以上で入力してください',
  TOO_LONG_PASSWORD: 'パスワードは128文字以下で入力してください',
  INVALID_PASSWORD: 'パスワードが不正です',
  REQUIRED_USER_NAME: 'ユーザー名を入力してください',
  TOO_LONG_USER_NAME: 'ユーザー名は128文字以下で入力してください',
  INVALID_USER_NAME: 'ユーザー名が不正です',
  SESSION_EXPIRED: 'セッションが期限切れです。再度ログインしてください',
  VALIDATION_ERROR: '入力内容に誤りがあります',
  RATE_LIMITED: 'しばらく時間をおいてから再度お試しください',
  UNAUTHORIZED: '未認証または未登録のユーザーです',
  SERVER_ERROR: 'サーバーエラーが発生しました',
  FAILED_SIGN_IN: 'ログインに失敗しました',
  FAILED_SIGN_UP: 'サインアップに失敗しました',
} as const satisfies Record<string, string>
